<?php

namespace Container7g4Cnli;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EKbW_HCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eKbW.HC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eKbW.HC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DatawarehouseController::clientAjout' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\DatawarehouseController::clientDetails' => ['privates', '.service_locator.ADSFHF9', 'get_ServiceLocator_ADSFHF9Service', true],
            'App\\Controller\\DatawarehouseController::clientListe' => ['privates', '.service_locator.CZ1jTUx', 'get_ServiceLocator_CZ1jTUxService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\DatawarehouseController:clientAjout' => ['privates', '.service_locator.ddnXYXj', 'get_ServiceLocator_DdnXYXjService', true],
            'App\\Controller\\DatawarehouseController:clientDetails' => ['privates', '.service_locator.ADSFHF9', 'get_ServiceLocator_ADSFHF9Service', true],
            'App\\Controller\\DatawarehouseController:clientListe' => ['privates', '.service_locator.CZ1jTUx', 'get_ServiceLocator_CZ1jTUxService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\DatawarehouseController::clientAjout' => '?',
            'App\\Controller\\DatawarehouseController::clientDetails' => '?',
            'App\\Controller\\DatawarehouseController::clientListe' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DatawarehouseController:clientAjout' => '?',
            'App\\Controller\\DatawarehouseController:clientDetails' => '?',
            'App\\Controller\\DatawarehouseController:clientListe' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
